version: "3.9"

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"  # Local mapping
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - PORT=8501      # Local override for docker-compose
