version: "3.9"

services:
  streamlit:
    build: .
    ports:
      - "8080:8080"  # Local mapping
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - PORT=8080      # Local override for docker-compose
